# Generated by Django 5.1.6 on 2025-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('pin', models.ImageField(upload_to='pins/', verbose_name='Pin')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
        ),
    ]
